### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Karthigeyankiruba** [KishoreSankar99/StrangersThings-quote-generator#1]
hello brother naanum B30  batch tha i dont have coding partners i have so much doubts from the beggining,i thought u can help me,because i cant raise query for basic doubts,if i have buddy its helps me to learn easily,help pannuvinganu namburan brother if you like to help me just mail me to this id  please karthigeyan0901@gmail.com we can speak..

**Comment by KishoreSankar99** [comment]
9790764943 , what's app me bro
